[package]
name = "advent_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "advent_2023"
path = "src/lib.rs"

[[bin]]
name = "d01p1"
path = "src/bin/d01p1.rs"

[dependencies]
regex = "1.5"
